#!/usr/bin/env python3
"""MAGMA Dashboard — query MAGMA API and write stats to Obsidian.

Usage: python obsidian-integration/scripts/dashboard.py
Set OBSIDIAN_VAULT_PATH in .env or as environment variable.
"""

import os, sys, json, urllib.request
from datetime import datetime

MAGMA_API = os.environ.get("MAGMA_API", "http://localhost:8765")

VAULT = os.environ.get("OBSIDIAN_VAULT_PATH")
if not VAULT:
    print("ERROR: OBSIDIAN_VAULT_PATH not set. Set it in .env or as environment variable.")
    sys.exit(1)

OUTPUT = os.path.join(VAULT, "magma-dashboard.md")


def api(path):
    url = f"{MAGMA_API}{path}"
    with urllib.request.urlopen(url, timeout=10) as r:
        return json.loads(r.read())


def main():
    stats = api("/stats")
    events = api("/events?limit=20")

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        "---",
        "title: MAGMA Memory Dashboard",
        f"updated: {now}",
        "type: query",
        "tags: [magma, memory, dashboard, auto]",
        "---",
        "",
        "# MAGMA Memory Dashboard",
        "",
        f"> Auto-refreshed | Last update: {now}",
        "",
        "## Core Stats",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Events | {stats['events_added']} |",
        f"| Nodes | {stats['nodes']} |",
        f"| Edges | {stats['edges']} |",
        f"| Vectors | {stats['vectors']} |",
        f"| Queries | {stats.get('queries_processed', 0)} |",
        "",
        "## Four-Graph Status",
        "",
        "| Graph | Type | Description |",
        "|-------|------|-------------|",
        "| Semantic | undirected | cos(v_i,v_j) > threshold |",
        "| Temporal | directed | strict time order |",
        "| Causal | directed | LLM inferred |",
        "| Entity | directed | event -> entity |",
        "",
        "## Recent Events (20)",
        "",
        "| Time | Content |",
        "|------|---------|",
    ]

    for e in events:
        ts = e.get("timestamp", "")[:16].replace("T", " ")
        content = e.get("content", "")[:100]
        lines.append(f"| {ts} | {content} |")

    lines.extend([
        "",
        "## Memory Growth",
        "",
        f"Nodes: `{stats['nodes']}` | Edges: `{stats['edges']}` | Vectors: `{stats['vectors']}`",
        f"Edge/Node ratio: `{stats['edges'] / max(stats['nodes'], 1):.1f}`",
        "",
        "> Auto-generated by magma-dashboard.py",
    ])

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[OK] Dashboard → {OUTPUT}")
    print(f"     {stats['nodes']} nodes, {stats['edges']} edges")


if __name__ == "__main__":
    main()
