#!/usr/bin/env python3
"""MAGMA Review Queue — trigger Slow Path inference and create Obsidian review notes.

Flow:
1. Query MAGMA for events without causal/entity edges
2. POST /events/{id}/infer for each
3. Write LLM's inference result as an Obsidian review note
4. User confirms/rejects -> edges written back

Usage: python obsidian-integration/scripts/review.py
Set OBSIDIAN_VAULT_PATH in .env or as environment variable.
"""

import os, sys, json, re, urllib.request
from pathlib import Path
from datetime import datetime

MAGMA_API = os.environ.get("MAGMA_API", "http://localhost:8765")

VAULT = os.environ.get("OBSIDIAN_VAULT_PATH")
if not VAULT:
    print("ERROR: OBSIDIAN_VAULT_PATH not set. Set it in .env or as environment variable.")
    sys.exit(1)

REVIEW_DIR = Path(VAULT) / "magma" / "reviews"


def api_get(path):
    url = f"{MAGMA_API}{path}"
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.loads(r.read())


def api_post(path, data=None):
    url = f"{MAGMA_API}{path}"
    body = json.dumps(data or {}).encode("utf-8")
    req = urllib.request.Request(url, data=body,
        headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read())


def main():
    events = api_get("/events?limit=30")
    os.makedirs(REVIEW_DIR, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    reviewed = 0
    for e in events:
        nid = e["node_id"]
        content = e.get("content", "")[:120]
        ts = e.get("timestamp", "")[:16]

        # Skip wiki-ingest events (already entity nodes)
        if "wiki-ingest" in str(e.get("session_id", "")):
            continue

        # Trigger slow path
        try:
            result = api_post(f"/events/{nid}/infer")
        except Exception:
            continue

        causal = result.get("causal", 0)
        entity = result.get("entity", 0)
        if causal == 0 and entity == 0:
            continue

        # Write review note
        safe_title = content[:60].replace("/", "-").replace(":", "-").replace("|", "-")
        filename = f"{ts[:10]}-{nid[:8]}.md"
        lines = [
            "---",
            "title: Review",
            "type: review",
            "tags: [magma, review, pending]",
            f"node_id: {nid}",
            f"event_time: {ts}",
            f"causal_edges: {causal}",
            f"entity_edges: {entity}",
            "status: pending",
            "---",
            "",
            f"# Review: {safe_title}",
            "",
            f"**Event:** {content}",
            f"**Time:** {ts}",
            f"**Node ID:** `{nid}`",
            "",
            "## Inferred Relations",
            "",
            f"- Causal edges: **{causal}**",
            f"- Entity edges: **{entity}**",
            "",
            "## Decision",
            "",
            "- [ ] Confirm (change `status: confirmed` in frontmatter)",
            "- [ ] Reject (change `status: rejected` in frontmatter)",
            "- [ ] Edit (correct the relations manually)",
            "",
            "> Auto-generated by MAGMA Review Queue",
        ]

        path = REVIEW_DIR / filename
        path.write_text("\n".join(lines), encoding="utf-8")
        reviewed += 1

    if reviewed:
        index_lines = [
            "---",
            "title: MAGMA Review Queue",
            f"updated: {now}",
            "type: query",
            "tags: [magma, review, meta]",
            "---",
            "",
            "# MAGMA Review Queue",
            "",
            f"> {reviewed} pending reviews | Updated: {now}",
            "",
        ]
        for f in sorted(REVIEW_DIR.glob("*.md"), reverse=True):
            content = f.read_text(encoding="utf-8")
            m = re.search(r'^status:\s*(\w+)', content, re.MULTILINE)
            status = m.group(1) if m else "unknown"
            if status == "pending":
                title = f.stem
                index_lines.append(f"- [ ] [[magma/reviews/{f.stem}|{title}]]")

        (REVIEW_DIR / "index.md").write_text("\n".join(index_lines), encoding="utf-8")
        print(f"[OK] {reviewed} review notes written to {REVIEW_DIR}")
    else:
        print("[OK] No new edges to review")


if __name__ == "__main__":
    main()
